# Generated by Django 3.2.6 on 2021-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211120_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=True, max_length=11, null=True),
        ),
    ]
